# Dockerfile
FROM node:17

# Crea el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de configuración de npm
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install --legacy-peer-deps

# Copia el resto del código fuente
COPY . .

# # Construye el proyecto si es necesario
# RUN npm run build

# Expone el puerto que tu aplicación utilizará
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["npm", "run", "serve"]
