version: '3.9'
services:
  db:
    image: "postgres:14-alpine"
    container_name: "db_postgres"
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    #   - /etc/backend-data-ddbb/data:/var/lib/postgresql/data
      - ./backend/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - management-team-net

  backend:
    container_name: "backend-web"
    build:
      context: ./backend
    ports:
      - "80:80"   # Mapeo para HTTP
      - "443:443" # Mapeo para HTTPS
    depends_on:
      - db
    environment:
      - API_PORT=80
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgresdb
    # volumes:
    #   - ./backend:/usr/src/app
      # - /usr/src/app/node_modules
    networks:
      - management-team-net
  
  frontend:
    container_name: "frontend-web"
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://localhost:80
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - management-team-net

networks:
  management-team-net:
    driver: bridge
