#Dockerfile
FROM node:17

# Crea el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de configuración de npm
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto del código fuente
COPY . .

# Construye el proyecto
RUN npm run build

# Expone el puerto que tu aplicación utilizará
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD [ "npm", "start" ]
